#!/usr/bin/env bash
# Deploy contracts to a local Stellar standalone network.
#
# Prerequisites:
#   - Docker running (for stellar container)
#   - stellar CLI installed
#   - Contracts built: stellar contract build (in each contract dir)
#
# Usage:
#   ./scripts/deploy-local.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

NETWORK="standalone"
NETWORK_PASSPHRASE="Standalone Network ; February 2017"
RPC_URL="http://localhost:8000/soroban/rpc"
IDENTITY="committee-local"

echo "=== Stellar Poker Local Deployment ==="
echo ""

# 1. Start Stellar standalone container if not already running
echo "Starting Stellar standalone network (Docker)..."
if ! docker ps --format '{{.Names}}' | grep -q stellar; then
    stellar container start "$NETWORK" 2>/dev/null || {
        echo "ERROR: Failed to start Stellar container. Is Docker running?"
        exit 1
    }
else
    echo "  Stellar container already running."
fi

# Wait for RPC to be ready
echo "Waiting for RPC to be ready..."
for i in $(seq 1 60); do
    if curl -sf "$RPC_URL" >/dev/null 2>&1; then
        echo "  RPC ready!"
        break
    fi
    if [ "$i" -eq 60 ]; then
        echo "ERROR: RPC not ready after 120s"
        exit 1
    fi
    sleep 2
done

# 2. Configure network in Stellar CLI
echo "Configuring network..."
stellar network add "$NETWORK" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" 2>/dev/null || true

# 3. Generate committee identity and fund it
echo "Generating committee identity..."
stellar keys generate "$IDENTITY" --network "$NETWORK" --fund 2>/dev/null || {
    echo "  Identity '$IDENTITY' may already exist, using existing."
}

COMMITTEE_SECRET=$(stellar keys show "$IDENTITY")
COMMITTEE_ADDRESS=$(stellar keys address "$IDENTITY")
echo "  Committee Address: $COMMITTEE_ADDRESS"

# 4. Build contracts
echo ""
echo "Building contracts..."
for contract_dir in zk-verifier poker-table committee-registry; do
    echo "  Building $contract_dir..."
    (cd "$PROJECT_DIR/contracts/$contract_dir" && stellar contract build 2>&1) || {
        echo "ERROR: Failed to build $contract_dir"
        exit 1
    }
done
echo "  All contracts built."

# 5. Deploy contracts
echo ""
echo "Deploying contracts..."

WASM_DIR="$PROJECT_DIR/target/wasm32-unknown-unknown/release"

echo "  Deploying zk-verifier..."
ZK_VERIFIER=$(stellar contract deploy \
    --wasm "$WASM_DIR/zk_verifier.wasm" \
    --source "$IDENTITY" \
    --network "$NETWORK")
echo "    ZK Verifier: $ZK_VERIFIER"

echo "  Deploying poker-table..."
POKER_TABLE=$(stellar contract deploy \
    --wasm "$WASM_DIR/poker_table.wasm" \
    --source "$IDENTITY" \
    --network "$NETWORK")
echo "    Poker Table: $POKER_TABLE"

echo "  Deploying committee-registry..."
COMMITTEE_REGISTRY=$(stellar contract deploy \
    --wasm "$WASM_DIR/committee_registry.wasm" \
    --source "$IDENTITY" \
    --network "$NETWORK")
echo "    Committee Registry: $COMMITTEE_REGISTRY"

# 6. Initialize zk-verifier
echo ""
echo "Initializing zk-verifier..."
stellar contract invoke \
    --id "$ZK_VERIFIER" \
    --source "$IDENTITY" \
    --network "$NETWORK" \
    -- initialize \
    --admin "$COMMITTEE_ADDRESS" || echo "  (may already be initialized)"

# 7. Upload verification keys (if they exist)
echo ""
echo "Uploading verification keys..."
for circuit in deal_valid reveal_board_valid showdown_valid; do
    VK_PATH="$PROJECT_DIR/circuits/$circuit/target/vk"
    if [ -f "$VK_PATH" ]; then
        VK_HEX=$(xxd -p "$VK_PATH" | tr -d '\n')
        # Map circuit name to contract enum variant
        case "$circuit" in
            deal_valid)         CIRCUIT_TYPE="DealValid" ;;
            reveal_board_valid) CIRCUIT_TYPE="RevealBoardValid" ;;
            showdown_valid)     CIRCUIT_TYPE="ShowdownValid" ;;
        esac
        echo "  Uploading VK for $circuit ($CIRCUIT_TYPE)..."
        stellar contract invoke \
            --id "$ZK_VERIFIER" \
            --source "$IDENTITY" \
            --network "$NETWORK" \
            -- set_verification_key \
            --admin "$COMMITTEE_ADDRESS" \
            --circuit "$CIRCUIT_TYPE" \
            --vk_data "$VK_HEX" || echo "    WARNING: VK upload failed for $circuit"
    else
        echo "  SKIP: No VK file at $VK_PATH (compile circuits first)"
    fi
done

# 8. Write environment file
ENV_FILE="$PROJECT_DIR/.env.local"
cat > "$ENV_FILE" << EOF
# Generated by deploy-local.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SOROBAN_RPC=$RPC_URL
POKER_TABLE_CONTRACT=$POKER_TABLE
ZK_VERIFIER_CONTRACT=$ZK_VERIFIER
COMMITTEE_REGISTRY_CONTRACT=$COMMITTEE_REGISTRY
COMMITTEE_SECRET=$COMMITTEE_SECRET
COMMITTEE_ADDRESS=$COMMITTEE_ADDRESS
NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE
EOF

echo ""
echo "=== Deployment Complete ==="
echo ""
echo "  Poker Table:        $POKER_TABLE"
echo "  ZK Verifier:        $ZK_VERIFIER"
echo "  Committee Registry: $COMMITTEE_REGISTRY"
echo "  Committee Address:  $COMMITTEE_ADDRESS"
echo ""
echo "  Environment written to: $ENV_FILE"
echo ""
echo "  Next: run ./scripts/start-local.sh to start services"
